---
title: "Find Meaningful Transfers"
output: html_notebook
---

```{r, eval=FALSE}
library(readr)
library(dplyr)
library(lubridate)
```

```{r}

od <- read_csv("origin_destination_route_device_sample.csv")
```

```{r}
od <- od %>% 
  group_by(cardid_anony) %>%
  mutate(count = n())

hist(od$count)
```

```{r}
t <- strftime(od$psttime, format="%H:%M:%S")
xx <- as.POSIXct(t, format="%H:%M:%S")

od$hour <- hour(xx)
od$minute <- minute(xx)
```

```{r}
od <- od %>% 
  group_by(cardid_anony) %>%
  mutate(timediff = difftime(psttime, lag(psttime),units="mins"))
```

```{r}
od <- od %>%
  select(cardid_anony, hour, minute, timediff, everything()) %>%
  arrange(cardid_anony, hour, minute, psttime) %>%
  mutate()
```

```{r}
od1 <- od %>% 
  filter(!is.na(timediff) & timediff<100)

od1$timediff <- as.integer(abs(od1$timediff))

hist(od1$timediff)
summary(od1$timediff)
```

```{r}
od2 <- od1 %>% 
  filter(timediff<70)

hist(od2$timediff)
```


```{r, eval=FALSE}
library(googlesheets)
iris_ss <- gs_new("iris", input = head(iris, 3), trim = TRUE)
```
