create table clipper_days.devices_{date_title}
SORTKEY(sequencenumber,
        deviceserialnumber,
        operatorid, 
        routeid, 
        generationtime)
AS SELECT generationtime,
        revenueservicedatetime,
        lastconnection,
        employeeid,
        installationid,
        operatorid,
        vehicleid,
        routeid,
        batchsequencenumber,
        locationid,
        txnrouteid,
        stationorlocation,
        avmnumber,
        numberof1notes,
        numberof5notes,
        numberof10notes,
        numberof20notes,
        numslavedevices,
        numberofcdfiles,
        envelopeheaderversion,
        recordtype,
        subtype,
        eventcode,
        securitymoduleid,
        deviceserialnumber,
        sequencenumber,
        udsequencenumber,
        cardserialnumber,
        operatorspecificdata1,
        operatorspecificdata2,
        operatorspecificdata3,
        operatorspecificdata4,
        pulledvaultserialnum,
        insertedvaultserialnum,
        amountpulled,
        newversion
FROM clipper.deviceeventswithdatatransaction 
    WHERE generationtime > '{start_date} {partition_time}'
    AND generationtime < '{end_date} {partition_time}';