select_vars1 <- c("cardid_anony",
                  "psttime",
                  "originlocation",
                  "destinationlocation",
                  "transferdiscountflag",
                  "transferoperator",
                  "productcategory",
                  "locationid",
                  "locationname",
                  "routeid_dvc",
                  "txnrouteid",
                  "routeid_tr",
                  "placeid",
                  "vehicleid_dvc",
                  "vehicleid_dvcl",
                  "vehicleid_tr",
                  "installdate",
                  "operatorid_dvc",
                  "operatorid_tr",
                  "tripsequencenumber",
                  "sequencenumber",
                  "avmnumber",
                  "recordtype_dvc",
                  "recordtype_tr",
                  "sublocation",
                  "subtype_dvc",
                  "subtype_tr")
#the following happen in a join
# "routename",
# "locationname.device",
# "locationname.origin",
# "participantname",
# "participantname.transfer",

select_vars2 <- c("cardid_anony",
                  "psttime",
                  "locationname.origin",
                  "locationname.destination",
                  "participantname",
                  "participantname.transfer",
                  "routename",
                  "locationname.device",
                  "routeid_dvc",
                  "txnrouteid",
                  "routeid_tr",
                  "placeid",
                  "vehicleid_dvc",
                  "vehicleid_dvcl",
                  "vehicleid_tr",
                  "installdate",
                  "operatorid_dvc",
                  "operatorid_tr",
                  "sublocation",
                  "subtype_dvc",
                  "subtype_tr",
                  "tripsequencenumber",
                  "sequencenumber",
                  "avmnumber",
                  "recordtype_dvc",
                  "recordtype_tr",
                  "originlocation",
                  "destinationlocation",
                  "transferdiscountflag",
                  "transferoperator",
                  "productcategory",
                  "locationid")
