select_vars1 <- c("cardid_anony",
                  "psttime",
                  "originlocation",
                  "destinationlocation",
                  "transferdiscountflag",
                  "transferoperator",
                  "productcategory",
                  "locationid",
                  "locationname",
                  "routeid_dvc",
                  "txnrouteid",
                  "routeid_tr",
                  "placeid",
                  "vehicleid_dvc",
                  "vehicleid_dvcl",
                  "vehicleid_tr",
                  "installdate",
                  "operatorid_dvc",
                  "operatorid_tr",
                  "tripsequencenumber",
                  "sequencenumber",
                  "avmnumber",
                  "recordtype_dvc",
                  "recordtype_tr",
                  "sublocation",
                  "subtype_dvc",
                  "subtype_tr")
#the following happen in a join
# "routename",
# "locationname.device",
# "locationname.origin",
# "participantname",
# "participantname.transfer",

select_vars2 <- c("cardid_anony",
                  "psttime",
                  "locationname.origin",
                  "locationname.destination",
                  "participantname",
                  "participantname.transfer",
                  "routename",
                  "locationname.device",
                  "routeid_dvc",
                  "txnrouteid",
                  "routeid_tr",
                  "placeid",
                  "vehicleid_dvc",
                  "vehicleid_dvcl",
                  "vehicleid_tr",
                  "installdate",
                  "operatorid_dvc",
                  "operatorid_tr",
                  "sublocation",
                  "subtype_dvc",
                  "subtype_tr",
                  "tripsequencenumber",
                  "sequencenumber",
                  "avmnumber",
                  "recordtype_dvc",
                  "recordtype_tr",
                  "originlocation",
                  "destinationlocation",
                  "transferdiscountflag",
                  "transferoperator",
                  "productcategory",
                  "locationid")

transaction_transfer_vars <- c("cardid_anony","hour","minute",
                          "yday","wday","month",
                          "is_bart","transfer_from_route",
                          "transfer_to_route",
                          "transfer_to_not_bart",
                          "transfer_from_not_bart",
                          "locationname.origin","locationname.destination",
                          "transfer_to_operator",
                          "transfer_from_operator",
                          "transfer_from_operator_time",
                          "transfer_to_operator_time",
                          "transferdiscountflag","transaction_count",
                          "bart_tr_count","tr_count_diff",
                          "timediff",
                          "operatorid_tr","participantname",
                          "routename","vehicleid_dvcl",
                          "installdate","sublocation",
                          "tripsequencenumber","sequencenumber")


bart_flattened_transfers_variables <- c("cardid_anony","hour","minute",
                                "yday","wday","month",
                                "locationname.origin","locationname.destination",
                                "transfer_to_operator","transfer_from_route",
                                "transfer_to_route",
                                "transfer_from_operator",
                                "transfer_from_operator_time",
                                "transfer_to_operator_time",
                                "transferdiscountflag",
                                "transaction_count",
                                "bart_tr_count","tr_count_diff")
