bart_journey_vars <- c("cardid_anony","transaction_time","time_of_previous",
                          "is_bart","transfer_from_route",
                          "transfer_to_route",
                          "transfer_to_not_bart",
                          "transfer_from_not_bart",
                          "locationname.origin","locationname.destination",
                          "transfer_to_operator",
                          "transfer_from_operator",
                          "transfer_from_operator_time",
                          "transfer_to_operator_time",
                          "timediff",
                          "operatorid","participantname",
                          "routename",
                          "tripsequencenumber","sequencenumber")

